<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\EntityInterface;

/**
 * BlogArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogArticleRepository extends EntityRepository
{
    public function add(EntityInterface $entity)
    {
        $this->getEntityManager()->persist($entity);
        $this->commit();
    }

    private function commit()
    {
        $this->getEntityManager()->flush();
    }
}
