parameters:

services:
    app.blog_article_repository:
        class: AppBundle\Repository\BlogArticleRepository
        factory: [@doctrine.orm.entity_manager, getRepository]
        arguments:
            - AppBundle\Entity\BlogArticle
